services:
  - type: web
    name: nfse-simulador
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: LOG_LEVEL
        value: info
      - key: PG_HOST
        sync: false
      - key: PG_PORT
        sync: false
      - key: PG_USER
        sync: false
      - key: PG_PASSWORD
        sync: false
      - key: PG_DATABASE
        sync: false
      - key: MONGO_URI
        sync: false
